#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#  user:
#      name: peter
#      password: verysecret
#      role: POWERFUL
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accounts?useOldAliasMetadataBehavior=true&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: changeme

facebook:
  client:
    clientId: 1839072669749820
    clientSecret: 7730785af9678b52bce125df90a6d1d9
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,first_name,last_name,email

github:
  client:
    clientId: 5c50edcb62654b025614
    clientSecret: fd79d0eebd330d8feec7e8972848bf95872c24f5
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: user:email
  resource:
    userInfoUri: https://api.github.com/user
#email url https://api.github.com/user/emails

google:
  client:
    clientId: 1018193966378-rmqrhc34vei36gtdgc7f74s37v0v64ma.apps.googleusercontent.com
    clientSecret: Sh-eO6q7jDzr3snolK66Eg4Z
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    tokenName: authorization_code
    scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo?fields=sub,given_name,family_name,email,gender

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.provider.endpoint: DEBUG
